version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/s-gen-crm
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRE=24h
      - JWT_COOKIE_EXPIRE=30
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: